name: Rails CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:  # Add the RAILS_MASTER_KEY environment variable here
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0

    - name: Bundle Install
      run: bundle install

    - name: Database Setup
      run: bundle exec rake db:create db:schema:load --trace

    - name: Run Tests
      run: bundle exec rspec

    - name: Install cc-test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter

    - name: Upload Coverage to Code Climate
      run: |
        ./cc-test-reporter before-build
        ./cc-test-reporter after-build --exit-code $?
