name: CI - Integrations
on:
  push:
    paths:
      - "integrations/**"

env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.2.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
        working-directory: ./integrations

      - name: Run tests with code coverage
        run: COVERAGE=true bundle exec rspec
        working-directory: ./integrations
